version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iskele360_db_v8
      POSTGRES_USER: iskele360_db_v8_user
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=iskele360_db_v8
      - DB_USER=iskele360_db_v8_user
      - DB_PASSWORD=your_password_here
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
