version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=dpg-d6ikbp5pdvs73fc5pig-a
      - DB_PORT=5432
      - DB_NAME=iskele360_db_v8
      - DB_USER=iskele360_db_v8_user
      - DB_PASS=K9iWuJiLfXTDyT7tAfdSLWsRWCyXmaUwb
      - UPSTASH_REDIS_REST_URL=https://magnetic-malamute-11416.upstash.io
      - UPSTASH_REDIS_REST_TOKEN=ASyYAAljcDExZTdjN2M1MTA4YjA0MDJhYWM1Mzg2MGVjZjc3ZTQxNHAxMzg2MGVjZjc3ZTQxNA
      - JWT_SECRET=iskele360v81257-src-v8-baran
      - JWT_EXPIRES_IN=1d
      - CLOUDINARY_CLOUD_NAME=dj0gdefhc
      - CLOUDINARY_API_KEY=814979256919438
      - CLOUDINARY_API_SECRET=HjXB-SE4pUmaGQH8vKlKf2XxH6U
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  iskele360_network:
    driver: bridge 