version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=dpg-d6ikbp5pdvs73fc5pig-a
      - DB_PORT=5432
      - DB_NAME=iskele360_db_v8
      - DB_USER=iskele360_db_v8_user
      - JWT_SECRET=baranreisgizlikey
      - JWT_EXPIRES_IN=24h
      - REDIS_HOST=red-cjvvvvvvvvvvvvvvvvvvvvvvvv.redis.render.com
      - REDIS_PORT=6379
      - REDIS_USERNAME=red-cjvvvvvvvvvvvvvvvvvvvvvvvv
      - CLOUDINARY_CLOUD_NAME=iskele360
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    container_name: iskele360-backend-v8
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./logs:/usr/src/app/logs
    networks:
      - iskele360-network

networks:
  iskele360-network:
    driver: bridge 