name: iskele360v7
description: İskele360 İş Yönetim Sistemi - Versiyon 7
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Durum Yönetimi
  provider: ^6.0.5
  
  # Ağ İşlemleri
  http: ^1.1.0
  dio: ^5.3.2
  socket_io_client: ^2.0.3+1
  
  # Depolama
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  
  # UI Bileşenleri
  cupertino_icons: ^1.0.5
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  
  # Yardımcı Kütüphaneler
  equatable: ^2.0.5
  uuid: ^3.0.7
  logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/ 