services:
  - type: web
    name: iskele360-api
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_PREFIX
        value: /api/v8
      - key: API_VERSION
        value: 8.0.0
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGODB_URI
        sync: false
      - key: DB_MAX_POOL_SIZE
        value: 10
      - key: DB_MIN_POOL_SIZE
        value: 2
      - key: DB_CONNECTION_TIMEOUT
        value: 5000
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 1000
      - key: MAX_FILE_SIZE
        value: 10mb
      - key: SLOW_QUERY_THRESHOLD_MS
        value: 1000
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /healthcheck
    domains:
      - api.iskele360.com
